### ISSUE TITLE
Cannot declare member function 'void MAX7219::MAX7219_ShutdownStop()' to have static linkage

### ISSUE THREAD

**Issue by buentead** [JemRF/max7219#1]
Thank you for your software. I have a little issue when using your library (v1.0.0). When compiling my script, I'm getting the following warning:
`
....\Arduino\libraries\max7219\max7219.cpp:159:48: warning: cannot declare member function 'void MAX7219::MAX7219_ShutdownStop()' to have static linkage [-fpermissive]
`
```cpp
static void MAX7219::MAX7219_ShutdownStop (void)
```
Although the code is running, I was wondering if it can be fixed.
Thank you
Adrian

**Comment by JemRF** [comment]
Will do, thanks for bringing to our attention. I don't get the warning with avr-g++. What compiler (or Arduino platform) are you using? 

If its annoying you just remove the word 'static' from line 159 of ....\Arduino\libraries\max7219\max7219.cpp and please let us know if the warning is resolved.

**Comment by buentead** [comment]
You are right, I forgot to mention my IDE. I'm using the Arduino 1.8.12 installed locally on a Windows 10 Pro v1909.

Yes, when I remove 'static' from line 159 I don't get any warnings anymore.

Thank you.

**Comment by JemRF** [comment]
Fixed in V2.0
