### ISSUE TITLE
Some typos found in max7219.cpp comment

### ISSUE THREAD

**Issue by pfred1** [JemRF/max7219#3]
I corrected what I found here

********************************************************************************
*
* Module     : max7219.cpp
* Author     : Jonathan Evans
* Description: MAX7219 LED Display Driver
*
* The MAX7219/MAX7221 are compact, serial input/output common-cathode display drivers that interface
* microprocessors (µPs) to 7-segment numeric LED displays of up to 8 digits, bar-graph displays, or 64 
* individual LEDs
* Datasheet  : https://datasheets.maximintegrated.com/en/ds/MAX7219-MAX7221.pdf
*
* Library Description
*
*  - This library implements the 7-segment numeric LED display of 8 digits 
*  - The host communicates with the MAX7219 using three signals: CLK (pin 10), CS (pin 11), DIN (pin 12). 
*  - Pins can be configured in max7219.h
*  - The MAX7219 is a SPI interface
*  - This library uses the bitbang method for communication with the MAX7219 
*
* Usage
*
* Three methods are exposed for use:
*  
*  1. Begin
*  This method initializes communication, takes the display out of test mode, clears the screen and sets intensity.
*  Intensity is set at maximum but can be configured in max7219.h
*  
*  2. DisplayChar(Digit, Value, DP)
*  This method displays a single value (character) in position DIGIT (0=right most digit, 7=left most digit)
*  
*  3. DisplayText(Text, Justify)
*  This method displays a text string (Text) either right justified (Justify=0) or left justified (Justify=1) 
*/

So compare all of that with the source file and update as you see fit.

This lbtary uses the buitbang method for communication with the MAX7219
changed to
This library uses the bitbang method for communication with the MAX7219

Intensity is set at maximum but can be coinfigured in max7219.h
changed to
Intensity is set at maximum but can be configured in max7219.h

This method displays a single value (charachter) in position DIGIT (0=right most digit, 7=left most digit)
changed to
This method displays a single value (character) in position DIGIT (0=right most digit, 7=left most digit)

This method displays a text string (Text) either right justified (Justify=0) ot left justified (Justify=1)
changed to
This method displays a text string (Text) either right justified (Justify=0) or left justified (Justify=1)

Just looks neater with less typos.

**Comment by JemRF** [comment]
Fixed in V2.0
